export const TODO_STATUS = "todo"
export const INPROGRESS_STATUS = "inprogress"
export const DONE_STATUS = "done"
export const ADD_CASE = "ADD"
export const CHANGE_STATUS_CASE = "CHANGE-STATUS"
export const CHANGE_TITLE_CASE = "CHANGE-TITLE"