export const TODO_STATUS = "todo"
export const INPROGRESS_STATUS = "inprogress"
export const DONE_STATUS = "done"
export const ADD = "ADD"
export const CHANGE_STATUS = "CHANGE-STATUS"
export const CHANGE_TITLE = "CHANGE-TITLE"